package views;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.plaf.RootPaneUI;

/**
 *
 * @author SUSENO-PC
 */
public class menuUtama extends javax.swing.JFrame {
        
    // waktu sekarang 
     private void setJam(){
        ActionListener listener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                jam.setText(new WaktuSekarang().getWkt());
            }
        };
        new Timer(1000, listener).start();
    }
    
     
    
    static boolean maximixed = true;
    int xMouse;
    int yMouse;


    
    public menuUtama() {
        initComponents();
        setJam();
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        btnminimize = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        btnMasterData = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        panelJam = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        panelMasterData = new javax.swing.JPanel();
        btndatabrg = new javax.swing.JButton();
        btndatasupplier = new javax.swing.JButton();
        btndatagdg = new javax.swing.JButton();
        btndatakategori = new javax.swing.JButton();
        panelTransaksi = new javax.swing.JPanel();
        btnbrgmasuk = new javax.swing.JButton();
        btnbrgkeluar = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        btnlaporanbrgmasuk = new javax.swing.JButton();
        btnlaporanbrgkeluar = new javax.swing.JButton();
        btnlaporanstokbrg = new javax.swing.JButton();
        btnlapdatasuplier = new javax.swing.JButton();
        jam = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelUtama.setBackground(new java.awt.Color(204, 204, 204));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUtamaMouseClicked(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama.setText("FORM GUDANG PT.RAJAWALI NUSINDO");
        labelNama.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelNamaMouseDragged(evt);
            }
        });
        labelNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNamaMousePressed(evt);
            }
        });

        btnminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px.png"))); // NOI18N
        btnminimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px.png"))); // NOI18N
        btnminimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnminimize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        btnMasterData.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMasterData.setText("  Master Data");
        btnMasterData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMasterData.setContentAreaFilled(false);
        btnMasterData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasterData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMasterData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMasterData.setOpaque(true);
        btnMasterData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseExited(evt);
            }
        });

        btnTransaksi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTransaksi.setText("  Transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setOpaque(true);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnLaporan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLaporan.setText("  Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setOpaque(true);
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelJamLayout = new javax.swing.GroupLayout(panelJam);
        panelJam.setLayout(panelJamLayout);
        panelJamLayout.setHorizontalGroup(
            panelJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelJamLayout.setVerticalGroup(
            panelJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClose.setText("Keluar");
        btnClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMasterData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelJam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMasterData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btndatabrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndatabrg.setText(" Data Barang");
        btndatabrg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btndatabrg.setContentAreaFilled(false);
        btndatabrg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndatabrg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndatabrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndatabrg.setOpaque(true);
        btndatabrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatabrgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatabrgMouseExited(evt);
            }
        });
        btndatabrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatabrgActionPerformed(evt);
            }
        });

        btndatasupplier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndatasupplier.setText(" Data Supplier");
        btndatasupplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btndatasupplier.setContentAreaFilled(false);
        btndatasupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndatasupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndatasupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndatasupplier.setOpaque(true);
        btndatasupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatasupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatasupplierMouseExited(evt);
            }
        });
        btndatasupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatasupplierActionPerformed(evt);
            }
        });

        btndatagdg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndatagdg.setText(" Data Gudang");
        btndatagdg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btndatagdg.setContentAreaFilled(false);
        btndatagdg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndatagdg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndatagdg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndatagdg.setOpaque(true);
        btndatagdg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatagdgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatagdgMouseExited(evt);
            }
        });
        btndatagdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatagdgActionPerformed(evt);
            }
        });

        btndatakategori.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndatakategori.setText(" Data Kategori");
        btndatakategori.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btndatakategori.setContentAreaFilled(false);
        btndatakategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndatakategori.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndatakategori.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndatakategori.setOpaque(true);
        btndatakategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatakategoriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatakategoriMouseExited(evt);
            }
        });
        btndatakategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatakategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMasterDataLayout = new javax.swing.GroupLayout(panelMasterData);
        panelMasterData.setLayout(panelMasterDataLayout);
        panelMasterDataLayout.setHorizontalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndatabrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btndatasupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btndatagdg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btndatakategori, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelMasterDataLayout.setVerticalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasterDataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btndatabrg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btndatasupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btndatagdg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btndatakategori, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnbrgmasuk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnbrgmasuk.setText(" Barang Masuk");
        btnbrgmasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnbrgmasuk.setContentAreaFilled(false);
        btnbrgmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbrgmasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnbrgmasuk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbrgmasuk.setOpaque(true);
        btnbrgmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbrgmasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbrgmasukMouseExited(evt);
            }
        });
        btnbrgmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrgmasukActionPerformed(evt);
            }
        });

        btnbrgkeluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnbrgkeluar.setText(" Barang Keluar");
        btnbrgkeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnbrgkeluar.setContentAreaFilled(false);
        btnbrgkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbrgkeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnbrgkeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbrgkeluar.setOpaque(true);
        btnbrgkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbrgkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbrgkeluarMouseExited(evt);
            }
        });
        btnbrgkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrgkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnbrgkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnbrgmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addComponent(btnbrgmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnbrgkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnlaporanbrgmasuk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlaporanbrgmasuk.setText(" Laporan Barang Masuk");
        btnlaporanbrgmasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlaporanbrgmasuk.setContentAreaFilled(false);
        btnlaporanbrgmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlaporanbrgmasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlaporanbrgmasuk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlaporanbrgmasuk.setOpaque(true);
        btnlaporanbrgmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporanbrgmasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporanbrgmasukMouseExited(evt);
            }
        });
        btnlaporanbrgmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanbrgmasukActionPerformed(evt);
            }
        });

        btnlaporanbrgkeluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlaporanbrgkeluar.setText(" Laporan Barang Keluar");
        btnlaporanbrgkeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlaporanbrgkeluar.setContentAreaFilled(false);
        btnlaporanbrgkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlaporanbrgkeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlaporanbrgkeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlaporanbrgkeluar.setOpaque(true);
        btnlaporanbrgkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporanbrgkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporanbrgkeluarMouseExited(evt);
            }
        });
        btnlaporanbrgkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanbrgkeluarActionPerformed(evt);
            }
        });

        btnlaporanstokbrg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlaporanstokbrg.setText(" Laporan Stok Barang");
        btnlaporanstokbrg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlaporanstokbrg.setContentAreaFilled(false);
        btnlaporanstokbrg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlaporanstokbrg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlaporanstokbrg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlaporanstokbrg.setOpaque(true);
        btnlaporanstokbrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporanstokbrgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporanstokbrgMouseExited(evt);
            }
        });
        btnlaporanstokbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanstokbrgActionPerformed(evt);
            }
        });

        btnlapdatasuplier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlapdatasuplier.setText(" Laporan Data Supplier");
        btnlapdatasuplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlapdatasuplier.setContentAreaFilled(false);
        btnlapdatasuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlapdatasuplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlapdatasuplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlapdatasuplier.setOpaque(true);
        btnlapdatasuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlapdatasuplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlapdatasuplierMouseExited(evt);
            }
        });
        btnlapdatasuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlapdatasuplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlaporanbrgkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnlaporanbrgmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnlaporanstokbrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnlapdatasuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addComponent(btnlaporanbrgmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnlaporanbrgkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnlaporanstokbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnlapdatasuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jam.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jam.setOpaque(true);

        tgl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgl.setOpaque(true);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jam.setText(new WaktuSekarang().getWkt());
        jam.setPreferredSize(new java.awt.Dimension(100,22));
        tgl.setText(new WaktuSekarang().getTgl());
        tgl.setPreferredSize(new java.awt.Dimension(120,22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        String ObjButton[] = {"YES","NO"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda yakin ingi keluar?","Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null,ObjButton,ObjButton[1]);
        if(pilihan == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMasterDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseClicked
        panelMasterData.setVisible(true);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnMasterDataMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        panelTransaksi.setVisible(true);
        panelMasterData.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        panelLaporan.setVisible(true);
        panelTransaksi.setVisible(false);
        panelMasterData.setVisible(false);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btndatabrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatabrgActionPerformed
        panelMasterData.setVisible(false);
        new dataBarang(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btndatabrgActionPerformed

    private void panelUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseClicked
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_panelUtamaMouseClicked

    private void btnMasterDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasterDataMouseEntered

    private void btnMasterDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasterDataMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btndatabrgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatabrgMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatabrgMouseEntered

    private void btndatabrgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatabrgMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatabrgMouseExited

    private void btndatasupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatasupplierMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatasupplierMouseEntered

    private void btndatasupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatasupplierMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatasupplierMouseExited

    private void btndatagdgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatagdgMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatagdgMouseEntered

    private void btndatagdgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatagdgMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatagdgMouseExited

    private void btndatakategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatakategoriMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatakategoriMouseEntered

    private void btndatakategoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatakategoriMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btndatakategoriMouseExited

    private void btnbrgmasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbrgmasukMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_btnbrgmasukMouseEntered

    private void btnbrgmasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbrgmasukMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbrgmasukMouseExited

    private void btnbrgkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbrgkeluarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbrgkeluarMouseEntered

    private void btnbrgkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbrgkeluarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbrgkeluarMouseExited

    private void btnlaporanbrgmasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanbrgmasukMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporanbrgmasukMouseEntered

    private void btnlaporanbrgmasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanbrgmasukMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporanbrgmasukMouseExited

    private void btnlaporanbrgkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanbrgkeluarMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporanbrgkeluarMouseEntered

    private void btnlaporanbrgkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanbrgkeluarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporanbrgkeluarMouseExited

    private void btnlaporanstokbrgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanstokbrgMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporanstokbrgMouseEntered

    private void btnlaporanstokbrgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanstokbrgMouseExited
        // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_btnlaporanstokbrgMouseExited

    private void btndatakategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatakategoriActionPerformed
        panelMasterData.setVisible(false);
        new dataKategori(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btndatakategoriActionPerformed

    private void labelNamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNamaMousePressed
//// TODO add your handling code here:
    }//GEN-LAST:event_labelNamaMousePressed

    private void labelNamaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNamaMouseDragged
 // TODO add your handling code here://
    }//GEN-LAST:event_labelNamaMouseDragged

    private void btndatagdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatagdgActionPerformed
        panelMasterData.setVisible(false);
        new dataGudang(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btndatagdgActionPerformed

    private void btndatasupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatasupplierActionPerformed
        panelMasterData.setVisible(false);
        new dataSupplier(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btndatasupplierActionPerformed

    private void btnbrgmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrgmasukActionPerformed
        panelTransaksi.setVisible(false);
        new transaksiBarangMasuk(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnbrgmasukActionPerformed

    private void btnbrgkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrgkeluarActionPerformed
        panelTransaksi.setVisible(false);
        new transaksiBarangKeluar(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnbrgkeluarActionPerformed

    private void btnlaporanbrgmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanbrgmasukActionPerformed
        panelLaporan.setVisible(false);
        new laporanBarangMasuk(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnlaporanbrgmasukActionPerformed

    private void btnlaporanbrgkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanbrgkeluarActionPerformed
        panelLaporan.setVisible(false);
        new laporanBarangKeluar(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnlaporanbrgkeluarActionPerformed

    private void btnlaporanstokbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanstokbrgActionPerformed
        panelLaporan.setVisible(false);
        new laporanStokBarang(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnlaporanstokbrgActionPerformed

    private void btnlapdatasuplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapdatasuplierMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlapdatasuplierMouseEntered

    private void btnlapdatasuplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlapdatasuplierMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlapdatasuplierMouseExited

    private void btnlapdatasuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlapdatasuplierActionPerformed
        panelLaporan.setVisible(false);
        new laporanDataSupplier(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnlapdatasuplierActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      // TODO add your handling code here: 
    }//GEN-LAST:event_formWindowOpened

    private void btnminimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizeActionPerformed
       this.setState(Frame.ICONIFIED); // TODO add your handling code here:
    }//GEN-LAST:event_btnminimizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuUtama mn = new menuUtama();
                mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mn.setVisible(true);
            }           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMasterData;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnbrgkeluar;
    private javax.swing.JButton btnbrgmasuk;
    private javax.swing.JButton btndatabrg;
    private javax.swing.JButton btndatagdg;
    private javax.swing.JButton btndatakategori;
    private javax.swing.JButton btndatasupplier;
    private javax.swing.JButton btnlapdatasuplier;
    private javax.swing.JButton btnlaporanbrgkeluar;
    private javax.swing.JButton btnlaporanbrgmasuk;
    private javax.swing.JButton btnlaporanstokbrg;
    private javax.swing.JButton btnminimize;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel labelNama;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelJam;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelMasterData;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
